spring:
  application:
    name: credit-engine

  datasource:
    url: jdbc:postgresql://localhost:5432/srm_credit_engine
    username: srm_user
    password: srm_password
    driver-class-name: org.postgresql.Driver

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo

    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080